sudo: required
dist: trusty
language: java
python:
  - '2.7'
jdk:
  - openjdk8
env:
  - JVMCI_VERSION=0.18
script:
  - env | sort
  # Only run build for a pull request or when pushing a tagged commit to master
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" -o "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ]; then ./build.sh; fi
after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat

# See https://docs.travis-ci.com/user/deployment/releases
before_deploy:
  - echo "ARCHIVE=${ARCHIVE}"
  - export ARCHIVE=`ls *.tar.gz`
deploy:
  provider: releases
  api_key:
    secure: Sz53hEQspb5PdroCmSe6WhqjFPGJmnJ6GwCuZlIB8rk+5rTVCd+zCopPh6UmxCTWEUfpUJRyDGmqbhwwHGfmm8r4hHrmUXkL8SzO1SEm8QWTiWerkNkk+/YyCylZGWRvDmyOOaS04HsrVAPIYKKyxUlKDIGKXlD4adtBpXWpOywgDv6nqPUREnzhDg4Xbff5L6jDaTCLxVHgY5HCIwxaiQEChpnGmvgJ1ZoeRpMjd/TPM+sU03Qa6aAPpL1GY1liGZkTPIWExznIPmjGHQbDXJ3NB173c+LRyzlmN5xE462U0Kwm0yT62k/OX8hyOIBoF6st9cvMxf6k8Xy5tP+o1/z9112ZnXe2d2F7bRqOiGaOm//+OJBGUChNuBH8fvHbQ58lWSfCbNEu3QibwJ+DihZhk9v3CpTqmu+gt92npTOmC7zqE8su4Blw1WkUaQ2pxGM5sk/xxaA/b73agB4Rc1aAXN+gsN+sr8Q0IMmDoiMyQLwOY5zTyBF8dpZ1SPLbhB4NeywY1K1VUpkkYKp3wTUtSgoTYEYzV05BJ13+21s0RSIgzMnSrpIPZEgRL46EWvWD0tLimh0irHEhuCJomYY0lGKGlwPRO3ABqFfsFIb+GRgrbBLzkKQ6CpC7JYo7jwfnms24qONP1DHb7V1ErYR79p7hi2Dp9yd8sX/P2ZQ=
  file:
     - ${ARCHIVE}
     - ${ARCHIVE}.sha1
  skip_cleanup: true
  on:
    tags: true
    repo: dougxc/openjdk8-jvmci-builder
